[bot]
emojiGuild = 748444397858717727  # It's actually the modmail server, but I won't tell anyone!
guild = 507304429255393322
prefix = "?"
tagPrefix = "??"

[channels]
actionLogCategory = 764817953463861288
alerts = 762016277572747275
botCommands = 523633816078647296
moderatorLog = 722561981990699129

ignoredChannels = [
    782940637124362281,  # Moderator Applications
    565822936712347658,  # Moderators
    722561981990699129,  # Moderation Log
    722698715697119243,  # Botland
    618964111132327937,  # Taintedland
    762016277572747275,  # Alerts
    746875064200462416   # Action Log (System Log)
]

[git]
directory = "./data/git"

tagsFileUrl = "https://github.com/FabricMC/community/blob/{BRANCH}{PATH}/{NAME}.ytag"
tagsRepoBranch = "main"
tagsRepoUrl = "https://github.com/FabricMC/community.git"
tagsRepoPath = "/tags"

[mappings]
directory = "./data/mappings"

mavenUrl = "https://maven.fabricmc.net/net/fabricmc/yarn/{VERSION}/yarn-{VERSION}-mergedv2.jar"
yarnUrl = "https://meta.fabricmc.net/v2/versions/yarn/{VERSION}?limit=1"

[roles]
admin = 507304850250268672
mod = 521758400980320278
traineeMod = 763389505779925032

muted = 599682161926471720

noMeta = 758802509438386216
noReactions = 656707181001048067
noRequests = 746823000929730660
noSupport = 731277600764198923

devLife = 758836903066992693

[liveUpdates]
minecraftChannels = [ 507304986921664533, 535180192960872458 ]
jiraChannels = [ 535180192960872458 ]
