[bot]
guild = 507304429255393322
prefix = "!"

[channels]
actionLog = 746875064200462416
alerts = 762016277572747275
botCommands = 523633816078647296
moderatorLog = 722561981990699129

ignoredChannels = [
    565822936712347658,  # Moderators
    722561981990699129,  # Moderation Log
    722698715697119243,  # Botland
    618964111132327937,  # Taintedland
    762016277572747275,  # Alerts
    746875064200462416   # Action Log
]

[roles]
admin = 507304850250268672
mod = 521758400980320278

muted = 599682161926471720

noMeta = 758802509438386216
noReactions = 656707181001048067
noRequests = 746823000929730660
noSupport = 731277600764198923

devLife = 758836903066992693

[live_updates]
minecraftChannels = [ 507304986921664533, 535180192960872458 ]
jiraChannels = [ 535180192960872458 ]
